### ISSUE TITLE
请问Readme中测试所在硬件平台？

### ISSUE THREAD

**Issue by DreamWaterFound** [ethan-li-coding/FasterStereoCuda-Library#1]
李博您好！看了Readme中您最近研究工作的效果，令我印象深刻。

我有个问题，诸如“数据2”中在Kitti 双目图像上计算得到的结果，其速率“95fps”是在何种硬件设备（CPU&GPU）上得到的呢？

希望我的问题能够得到李博的解答。非常感谢！

**Comment by ethan-li-coding** [comment]
NVIDIA GTX1080

**Comment by DreamWaterFound** [comment]
非常感谢！
